Public Class Form1
    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        TextBox2.Clear()
        For x = 1 To Len(TextBox1.Text)
            Select Case Mid(TextBox1.Text, x, 1)
                Case "Й"
                    TextBox2.Text = TextBox2.Text + "Q"
                Case "Ц"
                    TextBox2.Text = TextBox2.Text + "W"
                Case "У"
                    TextBox2.Text = TextBox2.Text + "E"
                Case "К"
                    TextBox2.Text = TextBox2.Text + "R"
                Case "Е"
                    TextBox2.Text = TextBox2.Text + "T"
                Case "Н"
                    TextBox2.Text = TextBox2.Text + "Y"
                Case "Г"
                    TextBox2.Text = TextBox2.Text + "U"
                Case "Ш"
                    TextBox2.Text = TextBox2.Text + "I"
                Case "Щ"
                    TextBox2.Text = TextBox2.Text + "O"
                Case "З"
                    TextBox2.Text = TextBox2.Text + "P"
                Case "Х"
                    TextBox2.Text = TextBox2.Text + "A"
                Case "Ї"
                    TextBox2.Text = TextBox2.Text + "S"
                Case "Ф"
                    TextBox2.Text = TextBox2.Text + "D"
                Case "І"
                    TextBox2.Text = TextBox2.Text + "F"
                Case "В"
                    TextBox2.Text = TextBox2.Text + "G"
                Case "А"
                    TextBox2.Text = TextBox2.Text + "H"
                Case "П"
                    TextBox2.Text = TextBox2.Text + "J"
                Case "Р"
                    TextBox2.Text = TextBox2.Text + "K"
                Case "О"
                    TextBox2.Text = TextBox2.Text + "L"
                Case "Л"
                    TextBox2.Text = TextBox2.Text + "Z"
                Case "Д"
                    TextBox2.Text = TextBox2.Text + "X"
                Case "Ж"
                    TextBox2.Text = TextBox2.Text + "C"
                Case "Є"
                    TextBox2.Text = TextBox2.Text + "V"
                Case "Я"
                    TextBox2.Text = TextBox2.Text + "B"
                Case "Ч"
                    TextBox2.Text = TextBox2.Text + "N"
                Case "С"
                    TextBox2.Text = TextBox2.Text + "M"
                Case "М"
                    TextBox2.Text = TextBox2.Text + "!"
                Case "И"
                    TextBox2.Text = TextBox2.Text + "@"
                Case "Т"
                    TextBox2.Text = TextBox2.Text + "#"
                Case "Ь"
                    TextBox2.Text = TextBox2.Text + "$"
                Case "Б"
                    TextBox2.Text = TextBox2.Text + "%"
                Case "Ю"
                    TextBox2.Text = TextBox2.Text + "^"
                Case " "
                    TextBox2.Text = TextBox2.Text + "&"
                Case ","
                    TextBox2.Text = TextBox2.Text + "*"
                Case "."
                    TextBox2.Text = TextBox2.Text + "("
                Case "й"
                    TextBox2.Text = TextBox2.Text + ")"
                Case "ц"
                    TextBox2.Text = TextBox2.Text + "_"
                Case "у"
                    TextBox2.Text = TextBox2.Text + "-"
                Case "к"
                    TextBox2.Text = TextBox2.Text + "+"
                Case "е"
                    TextBox2.Text = TextBox2.Text + "="
                Case "н"
                    TextBox2.Text = TextBox2.Text + "["
                Case "г"
                    TextBox2.Text = TextBox2.Text + "q"
                Case "ш"
                    TextBox2.Text = TextBox2.Text + "w"
                Case "щ"
                    TextBox2.Text = TextBox2.Text + "e"
                Case "з"
                    TextBox2.Text = TextBox2.Text + "r"
                Case "х"
                    TextBox2.Text = TextBox2.Text + "t"
                Case "ї"
                    TextBox2.Text = TextBox2.Text + "y"
                Case "ф"
                    TextBox2.Text = TextBox2.Text + "u"
                Case "і"
                    TextBox2.Text = TextBox2.Text + "i"
                Case "в"
                    TextBox2.Text = TextBox2.Text + "o"
                Case "а"
                    TextBox2.Text = TextBox2.Text + "p"
                Case "п"
                    TextBox2.Text = TextBox2.Text + "a"
                Case "р"
                    TextBox2.Text = TextBox2.Text + "s"
                Case "о"
                    TextBox2.Text = TextBox2.Text + "d"
                Case "л"
                    TextBox2.Text = TextBox2.Text + "f"
                Case "д"
                    TextBox2.Text = TextBox2.Text + "g"
                Case "ж"
                    TextBox2.Text = TextBox2.Text + "h"
                Case "є"
                    TextBox2.Text = TextBox2.Text + "j"
                Case "я"
                    TextBox2.Text = TextBox2.Text + "k"
                Case "ч"
                    TextBox2.Text = TextBox2.Text + "l"
                Case "с"
                    TextBox2.Text = TextBox2.Text + "z"
                Case "м"
                    TextBox2.Text = TextBox2.Text + "x"
                Case "и"
                    TextBox2.Text = TextBox2.Text + "c"
                Case "т"
                    TextBox2.Text = TextBox2.Text + "v"
                Case "ь"
                    TextBox2.Text = TextBox2.Text + "b"
                Case "б"
                    TextBox2.Text = TextBox2.Text + "n"
                Case "ю"
                    TextBox2.Text = TextBox2.Text + "m"


                Case "1"
                    TextBox2.Text = TextBox2.Text + "5"
                Case "2"
                    TextBox2.Text = TextBox2.Text + "№"
                Case "3"
                    TextBox2.Text = TextBox2.Text + "0"
                Case "4"
                    TextBox2.Text = TextBox2.Text + "7"
                Case "5"
                    TextBox2.Text = TextBox2.Text + "{"
                Case "6"
                    TextBox2.Text = TextBox2.Text + "}"
                Case "7"
                    TextBox2.Text = TextBox2.Text + "]"
                Case "8"
                    TextBox2.Text = TextBox2.Text + ">"
                Case "9"
                    TextBox2.Text = TextBox2.Text + "<"
                Case "0"
                    TextBox2.Text = TextBox2.Text + "?"


                Case "Q"
                    TextBox2.Text = TextBox2.Text + "Ь"
                Case "W"
                    TextBox2.Text = TextBox2.Text + "Т"
                Case "E"
                    TextBox2.Text = TextBox2.Text + "И"
                Case "R"
                    TextBox2.Text = TextBox2.Text + "М"
                Case "T"
                    TextBox2.Text = TextBox2.Text + "С"
                Case "Y"
                    TextBox2.Text = TextBox2.Text + "Ч"
                Case "U"
                    TextBox2.Text = TextBox2.Text + "Я"
                Case "I"
                    TextBox2.Text = TextBox2.Text + "Д"
                Case "O"
                    TextBox2.Text = TextBox2.Text + "Л"
                Case "P"
                    TextBox2.Text = TextBox2.Text + "О"
                Case "A"
                    TextBox2.Text = TextBox2.Text + "Р"
                Case "S"
                    TextBox2.Text = TextBox2.Text + "П"
                Case "D"
                    TextBox2.Text = TextBox2.Text + "А"
                Case "F"
                    TextBox2.Text = TextBox2.Text + "В"
                Case "G"
                    TextBox2.Text = TextBox2.Text + "І"
                Case "H"
                    TextBox2.Text = TextBox2.Text + "Ф"
                Case "J"
                    TextBox2.Text = TextBox2.Text + "З"
                Case "K"
                    TextBox2.Text = TextBox2.Text + "Щ"
                Case "L"
                    TextBox2.Text = TextBox2.Text + "Ш"
                Case "Z"
                    TextBox2.Text = TextBox2.Text + "Г"
                Case "X"
                    TextBox2.Text = TextBox2.Text + "Н"
                Case "C"
                    TextBox2.Text = TextBox2.Text + "Е"
                Case "V"
                    TextBox2.Text = TextBox2.Text + "К"
                Case "B"
                    TextBox2.Text = TextBox2.Text + "У"
                Case "N"
                    TextBox2.Text = TextBox2.Text + "Ц"
                Case "M"
                    TextBox2.Text = TextBox2.Text + "Й"


                Case "q"
                    TextBox2.Text = TextBox2.Text + "ь"
                Case "w"
                    TextBox2.Text = TextBox2.Text + "т"
                Case "e"
                    TextBox2.Text = TextBox2.Text + "и"
                Case "r"
                    TextBox2.Text = TextBox2.Text + "м"
                Case "t"
                    TextBox2.Text = TextBox2.Text + "с"
                Case "y"
                    TextBox2.Text = TextBox2.Text + "ч"
                Case "u"
                    TextBox2.Text = TextBox2.Text + "я"
                Case "i"
                    TextBox2.Text = TextBox2.Text + "д"
                Case "o"
                    TextBox2.Text = TextBox2.Text + "л"
                Case "p"
                    TextBox2.Text = TextBox2.Text + "о"
                Case "a"
                    TextBox2.Text = TextBox2.Text + "р"
                Case "s"
                    TextBox2.Text = TextBox2.Text + "п"
                Case "d"
                    TextBox2.Text = TextBox2.Text + "а"
                Case "f"
                    TextBox2.Text = TextBox2.Text + "в"
                Case "g"
                    TextBox2.Text = TextBox2.Text + "і"
                Case "h"
                    TextBox2.Text = TextBox2.Text + "ф"
                Case "j"
                    TextBox2.Text = TextBox2.Text + "з"
                Case "k"
                    TextBox2.Text = TextBox2.Text + "щ"
                Case "l"
                    TextBox2.Text = TextBox2.Text + "ш"
                Case "z"
                    TextBox2.Text = TextBox2.Text + "г"
                Case "x"
                    TextBox2.Text = TextBox2.Text + "н"
                Case "c"
                    TextBox2.Text = TextBox2.Text + "е"
                Case "v"
                    TextBox2.Text = TextBox2.Text + "к"
                Case "b"
                    TextBox2.Text = TextBox2.Text + "у"
                Case "n"
                    TextBox2.Text = TextBox2.Text + "ц"
                Case "m"
                    TextBox2.Text = TextBox2.Text + "й"
            End Select
        Next
        TextBox1.Clear()
    End Sub
    Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
        TextBox1.Clear()
        For x = 1 To Len(TextBox2.Text)
            Select Case Mid(TextBox2.Text, x, 1)
                Case "Q"
                    TextBox1.Text = TextBox1.Text + "Й"
                Case "W"
                    TextBox1.Text = TextBox1.Text + "Ц"
                Case "E"
                    TextBox1.Text = TextBox1.Text + "У"
                Case "R"
                    TextBox1.Text = TextBox1.Text + "К"
                Case "T"
                    TextBox1.Text = TextBox1.Text + "Е"
                Case "Y"
                    TextBox1.Text = TextBox1.Text + "Н"
                Case "U"
                    TextBox1.Text = TextBox1.Text + "Г"
                Case "I"
                    TextBox1.Text = TextBox1.Text + "Ш"
                Case "O"
                    TextBox1.Text = TextBox1.Text + "Щ"
                Case "P"
                    TextBox1.Text = TextBox1.Text + "З"
                Case "A"
                    TextBox1.Text = TextBox1.Text + "Х"
                Case "S"
                    TextBox1.Text = TextBox1.Text + "Ї"
                Case "D"
                    TextBox1.Text = TextBox1.Text + "Ф"
                Case "F"
                    TextBox1.Text = TextBox1.Text + "І"
                Case "G"
                    TextBox1.Text = TextBox1.Text + "В"
                Case "H"
                    TextBox1.Text = TextBox1.Text + "А"
                Case "J"
                    TextBox1.Text = TextBox1.Text + "П"
                Case "K"
                    TextBox1.Text = TextBox1.Text + "Р"
                Case "L"
                    TextBox1.Text = TextBox1.Text + "О"
                Case "Z"
                    TextBox1.Text = TextBox1.Text + "Л"
                Case "X"
                    TextBox1.Text = TextBox1.Text + "Д"
                Case "C"
                    TextBox1.Text = TextBox1.Text + "Ж"
                Case "V"
                    TextBox1.Text = TextBox1.Text + "Є"
                Case "B"
                    TextBox1.Text = TextBox1.Text + "Я"
                Case "N"
                    TextBox1.Text = TextBox1.Text + "Ч"
                Case "M"
                    TextBox1.Text = TextBox1.Text + "С"
                Case "!"
                    TextBox1.Text = TextBox1.Text + "М"
                Case "@"
                    TextBox1.Text = TextBox1.Text + "И"
                Case "#"
                    TextBox1.Text = TextBox1.Text + "Т"
                Case "$"
                    TextBox1.Text = TextBox1.Text + "Ь"
                Case "%"
                    TextBox1.Text = TextBox1.Text + "Б"
                Case "^"
                    TextBox1.Text = TextBox1.Text + "Ю"
                Case "&"
                    TextBox1.Text = TextBox1.Text + " "
                Case "*"
                    TextBox1.Text = TextBox1.Text + ","
                Case "("
                    TextBox1.Text = TextBox1.Text + "."
                Case ")"
                    TextBox1.Text = TextBox1.Text + "й"
                Case "_"
                    TextBox1.Text = TextBox1.Text + "ц"
                Case "-"
                    TextBox1.Text = TextBox1.Text + "у"
                Case "+"
                    TextBox1.Text = TextBox1.Text + "к"
                Case "="
                    TextBox1.Text = TextBox1.Text + "е"
                Case "["
                    TextBox1.Text = TextBox1.Text + "н"
                Case "q"
                    TextBox1.Text = TextBox1.Text + "г"
                Case "w"
                    TextBox1.Text = TextBox1.Text + "ш"
                Case "e"
                    TextBox1.Text = TextBox1.Text + "щ"
                Case "r"
                    TextBox1.Text = TextBox1.Text + "з"
                Case "t"
                    TextBox1.Text = TextBox1.Text + "х"
                Case "y"
                    TextBox1.Text = TextBox1.Text + "ї"
                Case "u"
                    TextBox1.Text = TextBox1.Text + "ф"
                Case "i"
                    TextBox1.Text = TextBox1.Text + "і"
                Case "o"
                    TextBox1.Text = TextBox1.Text + "в"
                Case "p"
                    TextBox1.Text = TextBox1.Text + "а"
                Case "a"
                    TextBox1.Text = TextBox1.Text + "п"
                Case "s"
                    TextBox1.Text = TextBox1.Text + "р"
                Case "d"
                    TextBox1.Text = TextBox1.Text + "о"
                Case "f"
                    TextBox1.Text = TextBox1.Text + "л"
                Case "g"
                    TextBox1.Text = TextBox1.Text + "д"
                Case "h"
                    TextBox1.Text = TextBox1.Text + "ж"
                Case "j"
                    TextBox1.Text = TextBox1.Text + "є"
                Case "k"
                    TextBox1.Text = TextBox1.Text + "я"
                Case "l"
                    TextBox1.Text = TextBox1.Text + "ч"
                Case "z"
                    TextBox1.Text = TextBox1.Text + "с"
                Case "x"
                    TextBox1.Text = TextBox1.Text + "м"
                Case "c"
                    TextBox1.Text = TextBox1.Text + "и"
                Case "v"
                    TextBox1.Text = TextBox1.Text + "т"
                Case "b"
                    TextBox1.Text = TextBox1.Text + "ь"
                Case "n"
                    TextBox1.Text = TextBox1.Text + "б"
                Case "m"
                    TextBox1.Text = TextBox1.Text + "ю"


                Case "5"
                    TextBox1.Text = TextBox1.Text + "1"
                Case "№"
                    TextBox1.Text = TextBox1.Text + "2"
                Case "0"
                    TextBox1.Text = TextBox1.Text + "3"
                Case "7"
                    TextBox1.Text = TextBox1.Text + "4"
                Case "{"
                    TextBox1.Text = TextBox1.Text + "5"
                Case "}"
                    TextBox1.Text = TextBox1.Text + "6"
                Case "]"
                    TextBox1.Text = TextBox1.Text + "7"
                Case ">"
                    TextBox1.Text = TextBox1.Text + "8"
                Case "<"
                    TextBox1.Text = TextBox1.Text + "9"
                Case "?"
                    TextBox1.Text = TextBox1.Text + "0"


                Case "Ь"
                    TextBox1.Text = TextBox1.Text + "Q"
                Case "Т"
                    TextBox1.Text = TextBox1.Text + "W"
                Case "И"
                    TextBox1.Text = TextBox1.Text + "E"
                Case "М"
                    TextBox1.Text = TextBox1.Text + "R"
                Case "С"
                    TextBox1.Text = TextBox1.Text + "T"
                Case "Ч"
                    TextBox1.Text = TextBox1.Text + "Y"
                Case "Я"
                    TextBox1.Text = TextBox1.Text + "U"
                Case "Д"
                    TextBox1.Text = TextBox1.Text + "I"
                Case "Л"
                    TextBox1.Text = TextBox1.Text + "O"
                Case "О"
                    TextBox1.Text = TextBox1.Text + "P"
                Case "Р"
                    TextBox1.Text = TextBox1.Text + "A"
                Case "П"
                    TextBox1.Text = TextBox1.Text + "S"
                Case "А"
                    TextBox1.Text = TextBox1.Text + "D"
                Case "В"
                    TextBox1.Text = TextBox1.Text + "F"
                Case "І"
                    TextBox1.Text = TextBox1.Text + "G"
                Case "Ф"
                    TextBox1.Text = TextBox1.Text + "H"
                Case "З"
                    TextBox1.Text = TextBox1.Text + "J"
                Case "Щ"
                    TextBox1.Text = TextBox1.Text + "K"
                Case "Ш"
                    TextBox1.Text = TextBox1.Text + "L"
                Case "Г"
                    TextBox1.Text = TextBox1.Text + "Z"
                Case "Н"
                    TextBox1.Text = TextBox1.Text + "X"
                Case "Е"
                    TextBox1.Text = TextBox1.Text + "C"
                Case "К"
                    TextBox1.Text = TextBox1.Text + "V"
                Case "У"
                    TextBox1.Text = TextBox1.Text + "B"
                Case "Ц"
                    TextBox1.Text = TextBox1.Text + "N"
                Case "Й"
                    TextBox1.Text = TextBox1.Text + "M"



                Case "ь"
                    TextBox1.Text = TextBox1.Text + "q"
                Case "т"
                    TextBox1.Text = TextBox1.Text + "w"
                Case "и"
                    TextBox1.Text = TextBox1.Text + "e"
                Case "м"
                    TextBox1.Text = TextBox1.Text + "r"
                Case "с"
                    TextBox1.Text = TextBox1.Text + "t"
                Case "ч"
                    TextBox1.Text = TextBox1.Text + "y"
                Case "я"
                    TextBox1.Text = TextBox1.Text + "u"
                Case "д"
                    TextBox1.Text = TextBox1.Text + "i"
                Case "л"
                    TextBox1.Text = TextBox1.Text + "o"
                Case "о"
                    TextBox1.Text = TextBox1.Text + "p"
                Case "р"
                    TextBox1.Text = TextBox1.Text + "a"
                Case "п"
                    TextBox1.Text = TextBox1.Text + "s"
                Case "а"
                    TextBox1.Text = TextBox1.Text + "d"
                Case "в"
                    TextBox1.Text = TextBox1.Text + "f"
                Case "і"
                    TextBox1.Text = TextBox1.Text + "g"
                Case "ф"
                    TextBox1.Text = TextBox1.Text + "h"
                Case "з"
                    TextBox1.Text = TextBox1.Text + "j"
                Case "щ"
                    TextBox1.Text = TextBox1.Text + "k"
                Case "ш"
                    TextBox1.Text = TextBox1.Text + "l"
                Case "г"
                    TextBox1.Text = TextBox1.Text + "z"
                Case "н"
                    TextBox1.Text = TextBox1.Text + "x"
                Case "е"
                    TextBox1.Text = TextBox1.Text + "c"
                Case "к"
                    TextBox1.Text = TextBox1.Text + "v"
                Case "у"
                    TextBox1.Text = TextBox1.Text + "b"
                Case "ц"
                    TextBox1.Text = TextBox1.Text + "n"
                Case "й"
                    TextBox1.Text = TextBox1.Text + "m"
            End Select
        Next
        TextBox2.Clear()
    End Sub

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load

    End Sub

    Private Sub TextBox1_TextChanged(sender As Object, e As EventArgs) Handles TextBox1.TextChanged

    End Sub
End Class
